basePath: /
definitions:
  schema.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact:
    email: nekohor@foxmail.com
    name: 王宇阳
  description: 提供与FSP平台基础业务有关的杂七杂八微服务
  title: 宇阳的杂七杂八微服务
  version: 0.0.1
paths:
  /api/v1/category/steelgrade:
    post:
      parameters:
      - default: '{"steelGrade":"M510L"}'
        description: 钢种牌号
        in: body
        name: steelGrade
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"code": 200, "data": {"steelGrade": "M510L", "category1":
            "商品材", "category2": "高强商品材", "category3": "大梁钢", "category4": ""}, "message":
            ""}'
          schema:
            $ref: '#/definitions/schema.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/schema.Response'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/schema.Response'
      security:
      - ApiKeyAuth: []
      summary: 根据钢种牌号查询钢种分类结果，目前有4个维度
      tags:
      - 查询数据
  /api/v1/unqualified/rollbreak:
    post:
      parameters:
      - default: '{"queryDate":"2021-05-20"}'
        description: 查询日期
        in: body
        name: queryDate
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"code": 200, "data": {"rollBreakCountTotal": 6}'
          schema:
            $ref: '#/definitions/schema.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/schema.Response'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/schema.Response'
      security:
      - ApiKeyAuth: []
      summary: 根据日期查询轧破甩尾统计数
      tags:
      - 查询数据
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
